# Generated by Django 2.1.3 on 2018-11-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOVitem', models.CharField(max_length=200)),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
    ]
